import torch
import numpy as np
import os
import argparse
from datetime import datetime

# Q8.8 Format Parameters
FRACTIONAL_BITS = 8
SCALE_FACTOR = 2 ** FRACTIONAL_BITS

def float_to_q88(val):
    """ Converts a float to Q8.8 fixed-point integer. """
    q_val = int(round(val * SCALE_FACTOR))
    # Clip to 16-bit signed integer range
    if q_val > 32767:
        q_val = 32767
    elif q_val < -32768:
        q_val = -32768
    return q_val

def extract_weights_and_biases(pth_file):
    """ Loads PyTorch state_dict and extracts weights and biases. """
    print(f"PyTorch modeli yukleniyor: {pth_file}")
    
    # Try to load the model (assumes it's a state_dict)
    try:
        # Load weights on CPU
        state_dict = torch.load(pth_file, map_location=torch.device('cpu'), weights_only=True)
    except Exception as e:
        print(f"Hata: Model yuklenemedi. Detay: {e}")
        return None
        
    # We expect 4 Linear layers (40->64, 64->32, 32->16, 16->3)
    # The keys usually look like 'fc1.weight', 'fc1.bias', etc.
    weights = []
    biases = []
    
    # Simple extraction: iterate over state_dict and separate weights/biases
    for key, tensor in state_dict.items():
        val = tensor.numpy()
        if 'weight' in key:
            # PyTorch shape for Linear is (out_features, in_features). 
            # We want (in_features, out_features) for VHDL usually, or handle in VHDL.
            # Assuming VHDL expects column-major or row-major based on your logic.
            # Let's transpose to (in_features, out_features) to match standard VHDL MAC loops.
            weights.append(val.T)
        elif 'bias' in key:
            biases.append(val)
            
    if len(weights) != 4 or len(biases) != 4:
        print(f"DIKKAT: Beklenen 4 katman (Weights/Biases) bulunamadi. Bulunan W: {len(weights)}, B: {len(biases)}")
        
    return weights, biases

def generate_vhdl_package(weights, biases, output_file="weights_pkg.vhd"):
    """ Generates VHDL package with Q8.8 weights. """
    print("VHDL paketi uretiliyor...")
    
    layer_sizes = [w.shape[0] for w in weights] + [weights[-1].shape[1]]
    print(f"Tespit edilen ag mimarisi: {layer_sizes}")
    
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    vhdl_code = f"""-- ==============================================================================
-- Auto-Generated MLP Weights Package (Q8.8 Fixed-Point)
-- Generated by pth_to_vhdl.py on {now}
-- ==============================================================================

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

package weights_pkg is

    -- Data types
    type weight_array_l1 is array (0 to {weights[0].shape[0]*weights[0].shape[1]-1}) of signed(15 downto 0);
    type bias_array_l1 is array (0 to {biases[0].shape[0]-1}) of signed(15 downto 0);

    type weight_array_l2 is array (0 to {weights[1].shape[0]*weights[1].shape[1]-1}) of signed(15 downto 0);
    type bias_array_l2 is array (0 to {biases[1].shape[0]-1}) of signed(15 downto 0);

    type weight_array_l3 is array (0 to {weights[2].shape[0]*weights[2].shape[1]-1}) of signed(15 downto 0);
    type bias_array_l3 is array (0 to {biases[2].shape[0]-1}) of signed(15 downto 0);

    type weight_array_l4 is array (0 to {weights[3].shape[0]*weights[3].shape[1]-1}) of signed(15 downto 0);
    type bias_array_l4 is array (0 to {biases[3].shape[0]-1}) of signed(15 downto 0);

"""

    # Generate constants for each layer
    for layer_idx, (w, b) in enumerate(zip(weights, biases)):
        l_num = layer_idx + 1
        
        # Flatten weights and convert to Q8.8
        w_flat = w.flatten()
        w_q88 = [float_to_q88(val) for val in w_flat]
        
        b_q88 = [float_to_q88(val) for val in b]
        
        # Add weights
        vhdl_code += f"    constant LAYER{l_num}_WEIGHTS : weight_array_l{l_num} := (\n"
        w_str_list = [f'to_signed({val}, 16)' for val in w_q88]
        # Group by 10 for readability
        for i in range(0, len(w_str_list), 10):
            chunk = w_str_list[i:i+10]
            vhdl_code += "        " + ", ".join(chunk) + ("," if i+10 < len(w_str_list) else "") + "\n"
        vhdl_code += "    );\n\n"
        
        # Add biases
        vhdl_code += f"    constant LAYER{l_num}_BIASES : bias_array_l{l_num} := (\n"
        b_str_list = [f'to_signed({val}, 16)' for val in b_q88]
        for i in range(0, len(b_str_list), 10):
            chunk = b_str_list[i:i+10]
            vhdl_code += "        " + ", ".join(chunk) + ("," if i+10 < len(b_str_list) else "") + "\n"
        vhdl_code += "    );\n\n"

    vhdl_code += "end package weights_pkg;\n"
    
    with open(output_file, 'w') as f:
        f.write(vhdl_code)
        
    print(f"Basarili! VHDL paketi {output_file} olarak kaydedildi.")
    print("Bu dosyayi Vivado projenizdeki weights_pkg.vhd ile degistirip FPGA'yi tekrar sentezleyebilirsiniz.")

def main():
    parser = argparse.ArgumentParser(description="PyTorch (.pth) modelini VHDL (Q8.8) paketine donusturur.")
    parser.add_argument("--model", required=True, help="PyTorch .pth dosyasinin yolu")
    parser.add_argument("--output", default="weights_pkg.vhd", help="Cikti VHDL dosyasinin yolu")
    
    args = parser.parse_args()
    
    if not os.path.exists(args.model):
        print(f"Hata: Model dosyasi bulunamadi: {args.model}")
        return
        
    res = extract_weights_and_biases(args.model)
    if res:
        weights, biases = res
        generate_vhdl_package(weights, biases, args.output)

if __name__ == "__main__":
    main()
